### ISSUE TITLE
Setup a milestone for v1.0.0

### ISSUE THREAD

**Issue by MicroDroid** [devsnek/edge#2]
Well, it'd be nice to know how far is this project from fully supporting things.

**Comment by devsnek** [comment]
i haven't started making releases yet so i'm a far way off from even worrying about versioning. once i have the readme stuff finished and i can reliably make builds on a ci for mac and linux i think that will be 0.0.1

**Comment by devsnek** [comment]
alright i did it with #4 #5 #6 #7 #8 #9
